# A simple prompt that includes all R files

include_files  = '''
*.R
*.r
'''

# To save to the project root, use a simple filename like:
# opt_prompt_file = "my_prompt.md"
opt_prompt_file = "<tempdir>/files2prompt.md"
